export enum Step {
  INITIALIZING = "INITIALIZING",
  READY = "READY",
  CONNECTING = "CONNECTING",
  REPAIR_PARTITION_TABLES = "REPAIR_PARTITION_TABLES",
  ERASE_DEVICE = "ERASE_DEVICE",
  FLASH_SYSTEM = "FLASH_SYSTEM",
  FINALIZING = "FINALIZING",
  DONE = "DONE",
}

export enum Error {
  NONE = "NONE",
  UNKNOWN = "UNKNOWN",
  REQUIREMENTS_NOT_MET = "REQUIREMENTS_NOT_MET",
  STORAGE_SPACE = "STORAGE_SPACE",
  UNRECOGNIZED_DEVICE = "UNRECOGNIZED_DEVICE",
  LOST_CONNECTION = "LOST_CONNECTION",
  REPAIR_PARTITION_TABLES_FAILED = "REPAIR_PARTITION_TABLES_FAILED",
  ERASE_FAILED = "ERASE_FAILED",
  FLASH_SYSTEM_FAILED = "FLASH_SYSTEM_FAILED",
}

export interface StepConfig {
  status: string;
  description?: string;
  bgColor: string;
  icon: string;
  iconStyle?: string;
}
